(() => {
  'use strict';
  const KEY='ra9mana-editor-projects-v1';
  const LANGS={fr:{new:'Nouveau travail juridique',words:'mots',pages:'pages',notes:'tḥmīsh',saved:'Enregistré localement',search:'Rechercher dans la bibliothèque…',add:'Ajouter',manual:'Entrer manuellement',close:'Fermer',full:'Citation complète',short:'Citation abrégée',bib:'Bibliographie'},en:{new:'New legal work',words:'words',pages:'pages',notes:'footnotes',saved:'Saved locally',search:'Search the library…',add:'Add',manual:'Enter manually',close:'Close',full:'Full citation',short:'Short citation',bib:'Bibliography'},ar:{new:'عمل قانوني جديد',words:'كلمة',pages:'صفحات',notes:'تهميش',saved:'تم الحفظ محليًا',search:'ابحث في المكتبة…',add:'إضافة',manual:'إدخال يدوي',close:'إغلاق',full:'التهميش الكامل',short:'التهميش المختصر',bib:'قائمة المراجع'}};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const lang=()=> (window.RA9MANA_I18N&&RA9MANA_I18N.getLang?RA9MANA_I18N.getLang():localStorage.getItem('ra9mana-lang')||'fr');
  let project=createProject(); let currentPage=0; let library=[]; let autosaveTimer;
  function uid(prefix='x'){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
  function createPage(){return {id:uid('page'),html:'',footnotes:[]}}
  function createProject(){return {version:1,id:uid('project'),title:LANGS.fr.new,updatedAt:new Date().toISOString(),pages:[createPage()]}}
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function getProjects(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}
  function saveProjects(list){localStorage.setItem(KEY,JSON.stringify(list))}
  function persist(){project.title=$('#project-title').value.trim()||LANGS[lang()].new;project.updatedAt=new Date().toISOString(); const list=getProjects().filter(x=>x.id!==project.id);list.unshift(project);saveProjects(list.slice(0,30));$('#save-status').textContent=LANGS[lang()].saved;clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>$('#save-status').textContent='Auto-saved',900)}
  function capture(){ $$('.page-content').forEach((el,i)=>{if(project.pages[i])project.pages[i].html=el.innerHTML}); $$('.page').forEach((el,i)=>{if(project.pages[i]){project.pages[i].footnotes=JSON.parse(el.dataset.footnotes||'[]')}});persist();updateStats() }
  function render(){ $('#project-title').value=project.title;const root=$('#pages');root.innerHTML='';project.pages.forEach((p,i)=>{const page=document.createElement('section');page.className='page';page.dataset.index=i;page.dataset.footnotes=JSON.stringify(p.footnotes||[]);page.innerHTML=`<div class="page-head"><span>RA9MANA Legal Editor</span><span>Page ${i+1}</span></div><div class="page-actions"><button data-delete-page="${i}" title="Delete page">× Page</button></div><div class="page-content" contenteditable="true" spellcheck="true"></div><div class="page-footnotes"></div>`;page.querySelector('.page-content').innerHTML=p.html||'';renderFootnotes(page,p.footnotes||[]);root.appendChild(page)});bindPages();updateStats()}
  function renderFootnotes(page,notes){const box=page.querySelector('.page-footnotes');box.innerHTML=notes.map((n,i)=>`<div class="footnote-item" data-note-id="${escapeHtml(n.id)}"><span class="footnote-number">${i+1}.</span>${escapeHtml(n.text)} <button data-delete-note="${escapeHtml(n.id)}" title="Delete">×</button></div>`).join('') ;page.dataset.footnotes=JSON.stringify(notes)}
  function bindPages(){ $$('.page-content').forEach(el=>el.addEventListener('focusin',()=>{currentPage=Number(el.closest('.page').dataset.index||0)})); $$('.page-content').forEach(el=>el.addEventListener('input',()=>{currentPage=Number(el.closest('.page').dataset.index||0);capture()})); $$('.page-content').forEach(el=>el.addEventListener('mouseup',rememberSelection)); $$('.page-content').forEach(el=>el.addEventListener('keyup',rememberSelection)); $$('[data-delete-page]').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.deletePage;if(project.pages.length===1)return toast('يجب أن تبقى صفحة واحدة');project.pages.splice(i,1);render();persist()})); $$('[data-delete-note]').forEach(b=>b.addEventListener('click',()=>{const page=b.closest('.page'),notes=JSON.parse(page.dataset.footnotes||'[]').filter(n=>n.id!==b.dataset.deleteNote);project.pages[+page.dataset.index].footnotes=notes;renderFootnotes(page,notes);capture()})) }
  let savedRange=null;function rememberSelection(){const s=getSelection();if(s&&s.rangeCount&&$('.page-content')?.contains(s.anchorNode)){savedRange=s.getRangeAt(0).cloneRange()}}
  function restoreSelection(){if(!savedRange)return;const s=getSelection();s.removeAllRanges();s.addRange(savedRange)}
  function exec(cmd,val=null){restoreSelection();if(cmd==='createLink'){const url=prompt('URL');if(url)document.execCommand(cmd,false,url)}else document.execCommand(cmd,false,val);capture()}
  function addPage(){capture();project.pages.push(createPage());render();setTimeout(()=>{$$('.page-content').at(-1)?.focus();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})},50);persist()}
  async function loadLibrary(){try{const r=await fetch('data/library.json',{cache:'no-store'});library=await r.json();if(!Array.isArray(library))library=[]}catch{library=[]}}
  function openModal(html){$('#modal-content').innerHTML=html;$('#editor-modal').classList.add('is-open');$('#editor-modal').setAttribute('aria-hidden','false')}
  function closeModal(){$('#editor-modal').classList.remove('is-open');$('#editor-modal').setAttribute('aria-hidden','true')}
  function refText(ref,kind='full',pageNo=null){if(window.RA9MANA_CITATION){try{return window.RA9MANA_CITATION[kind](ref,lang())+(pageNo?`, p. ${pageNo}`:'')}catch{}}let author=ref.author&&ref.author!=='/'?ref.author:'';return [author,ref.title,ref.source,ref.year].filter(Boolean).join(', ')+(pageNo?`, p. ${pageNo}`:'')}
  function addMarker(page,number){restoreSelection();const content=page.querySelector('.page-content');if(!content)return;content.focus();if(savedRange){const r=savedRange.cloneRange();r.collapse(false);const a=document.createElement('a');a.className='reference-marker';a.textContent=number;a.href='#';a.title='Footnote '+number;a.addEventListener('click',e=>e.preventDefault());r.insertNode(a);r.setStartAfter(a);r.collapse(true);const s=getSelection();s.removeAllRanges();s.addRange(r)}else document.execCommand('insertHTML',false,`<sup class="reference-marker">${number}</sup>`)}
  function addFootnote(ref,text){const page=$$('.page')[currentPage]||$('.page');const notes=JSON.parse(page.dataset.footnotes||'[]');const number=notes.length+1;notes.push({id:uid('note'),refId:ref?.id||null,ref:ref||null,text:text||refText(ref,'full')});project.pages[currentPage].footnotes=notes;addMarker(page,number);renderFootnotes(page,notes);capture();closeModal();toast('تمت إضافة التهميش إلى الصفحة '+(currentPage+1))}
  function picker(){const l=LANGS[lang()];openModal(`<h2 class="modal-title">📚 ${lang()==='ar'?'إضافة مرجع من مكتبة RA9MANA':'Add a reference from RA9MANA Library'}</h2><p class="modal-sub">${l.search}</p><input class="library-picker-search" id="ref-search" placeholder="${l.search}"><div class="picker-filters" id="ref-filters"></div><div class="picker-list" id="ref-list"></div><div style="margin-top:15px"><button class="btn btn-ghost" id="manual-ref">✍️ ${l.manual}</button></div>`);let type='all';const types=[...new Set(library.map(r=>r.type).filter(Boolean))];$('#ref-filters').innerHTML=`<button class="picker-chip active" data-type="all">All</button>`+types.map(t=>`<button class="picker-chip" data-type="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join('');const draw=()=>{const q=($('#ref-search').value||'').toLowerCase();const arr=library.filter(r=>(type==='all'||r.type===type)&&[r.title,r.author,r.category,r.description,r.source].join(' ').toLowerCase().includes(q)).slice(0,60);$('#ref-list').innerHTML=arr.length?arr.map(r=>`<div class="picker-item"><div><h4>${escapeHtml(r.title||'—')}</h4><p>${escapeHtml([r.author&&r.author!=='/'?r.author:'',r.year,r.category].filter(Boolean).join(' · '))}</p></div><div class="picker-actions"><button data-use-ref="${escapeHtml(r.id)}">${l.add}</button><button class="secondary" data-foot-ref="${escapeHtml(r.id)}">¹</button></div></div>`).join(''):`<div class="ramon-box">${lang()==='ar'?'لم نجد هذا المرجع. يمكنك إدخاله يدويًا.':'No matching reference. You can enter it manually.'}</div>`;$$('[data-use-ref]').forEach(b=>b.onclick=()=>insertReference(library.find(r=>r.id===b.dataset.useRef)));$$('[data-foot-ref]').forEach(b=>b.onclick=()=>chooseFootnote(library.find(r=>r.id===b.dataset.footRef))) };$('#ref-search').oninput=draw;$$('[data-type]').forEach(b=>b.onclick=()=>{type=b.dataset.type;$$('[data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});$('#manual-ref').onclick=manualForm;draw()}
  function insertReference(ref){if(!ref)return;restoreSelection();const text=ref.title||'Référence';const page=$$('.page')[currentPage];page.querySelector('.page-content').focus();document.execCommand('insertText',false,text);capture();closeModal();toast('تمت إضافة المرجع إلى النص')}
  function chooseFootnote(ref){if(!ref)return;const previous=project.pages.flatMap(p=>p.footnotes||[]).find(n=>n.refId===ref.id);const options=previous?`<button class="btn btn-primary" id="use-full">${LANGS[lang()].full}</button><button class="btn btn-ghost" id="use-short">${LANGS[lang()].short}</button>`:`<button class="btn btn-primary" id="use-full">${LANGS[lang()].full}</button>`;openModal(`<h2 class="modal-title">¹ ${lang()==='ar'?'إضافة تهميش':'Add footnote'}</h2><p class="modal-sub">${escapeHtml(ref.title)}</p><div class="ramon-box"><p>${escapeHtml(refText(ref,'full'))}</p><div class="form-actions">${options}</div></div>`);$('#use-full').onclick=()=>addFootnote(ref,refText(ref,'full'));$('#use-short').onclick=()=>addFootnote(ref,refText(ref,'short'))}
  function manualForm(){openModal(`<h2 class="modal-title">✍️ ${LANGS[lang()].manual}</h2><p class="modal-sub">أدخل بيانات المرجع مرة واحدة وسيتم استخدامه في هذا المشروع.</p><form class="manual-form" id="manual-reference-form"><label>المؤلف<input name="author"></label><label>العنوان<input name="title" required></label><label>النوع<select name="type"><option value="book">كتاب</option><option value="law">قانون</option><option value="article">مقال</option><option value="thesis">مذكرة/أطروحة</option><option value="other">أخرى</option></select></label><label>المصدر / الناشر<input name="source"></label><label>السنة<input name="year"></label><label>الصفحة<input name="page"></label><div class="form-actions"><button type="button" class="btn btn-ghost" data-close-editor-modal>إلغاء</button><button class="btn btn-primary">إضافة التهميش</button></div></form>`);$('#manual-reference-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const r={id:uid('manual'),author:d.get('author'),title:d.get('title'),type:d.get('type'),source:d.get('source'),year:d.get('year')};addFootnote(r,[d.get('author'),d.get('title'),d.get('source'),d.get('year'),d.get('page')?`ص. ${d.get('page')}`:''].filter(Boolean).join(', '))}}
  function bibliography(){capture();const seen=new Map();project.pages.flatMap(p=>p.footnotes||[]).forEach(n=>{const r=(n.refId&&library.find(x=>x.id===n.refId))||n.ref;if(r){const key=n.refId||r.id||n.id;if(!seen.has(key))seen.set(key,r)}});const refs=[...seen.values()];openModal(`<h2 class="modal-title">📖 ${LANGS[lang()].bib}</h2><p class="modal-sub">تم جمع المصادر المستخدمة في التهميش تلقائيًا.</p>${refs.length?refs.map((r,i)=>`<div class="bib-item"><b>${i+1}. ${escapeHtml(refText(r,'bibliography'))}</b></div>`).join(''):'<div class="ramon-box">لم تتم إضافة مراجع من مكتبة RA9MANA بعد.</div>'}<div class="form-actions"><button class="btn btn-primary" id="copy-bib">نسخ القائمة</button></div>`);$('#copy-bib').onclick=()=>copyText(refs.map((r,i)=>`${i+1}. ${refText(r,'bibliography')}`).join('\n'))}
  function projectsModal(){const ps=getProjects();openModal(`<h2 class="modal-title">📂 ${lang()==='ar'?'مشاريعي':'My projects'}</h2><p class="modal-sub">${lang()==='ar'?'مشاريع محفوظة على هذا الجهاز فقط.':'Projects stored on this device only.'}</p><div class="project-list">${ps.length?ps.map(p=>`<div class="project-row"><div><b>${escapeHtml(p.title)}</b><small style="display:block;color:#64748b">${new Date(p.updatedAt).toLocaleString()}</small></div><button data-open-project="${escapeHtml(p.id)}">فتح</button></div>`).join(''):'<div class="ramon-box">لا توجد مشاريع محفوظة بعد.</div>'}</div>`);$$('[data-open-project]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.openProject);if(p){project=p;currentPage=0;render();closeModal();}})}
  function ramon(){const l=lang();openModal(`<div class="ramon-box"><h2 class="modal-title">🤖 رقمون داخل المحرر</h2><p>${l==='ar'?'أنا رقمون. أستطيع مساعدتك في العثور على مرجع، إضافة تهميش أو بناء قائمة المراجع.':'Je suis رقمون. I can help you find references, add footnotes and build your bibliography.'}</p><div class="ramon-actions"><button data-ramon-action="ref">📚 ${l==='ar'?'ابحث عن مرجع':'Find a reference'}</button><button data-ramon-action="note">¹ ${l==='ar'?'أضف تهميشًا':'Add a footnote'}</button><button data-ramon-action="bib">📖 ${l==='ar'?'قائمة المراجع':'Bibliography'}</button></div></div>`);$$('[data-ramon-action]').forEach(b=>b.onclick=()=>{closeModal();if(b.dataset.ramonAction==='ref')picker();if(b.dataset.ramonAction==='note')openFootnote();if(b.dataset.ramonAction==='bib')bibliography()})}
  function openFootnote(){currentPage=Number($('.page:focus-within')?.dataset.index||0);picker()}
  function exportProject(){capture();const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'});download(blob,(project.title||'ra9mana-project').replace(/[^\w\-\u0600-\u06ff]+/g,'-')+'.ra9mana')}
  function importProject(){ $('#project-file').click() }
  $('#project-file').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.pages)throw Error();project=p;render();persist();toast('تم استيراد المشروع')}catch{toast('ملف مشروع غير صالح')}};r.readAsText(f);e.target.value=''}
  function exportWord(){capture();const body=project.pages.map((p,i)=>`<div style="page-break-after:always;padding:50px"><h4>RA9MANA Legal Editor — Page ${i+1}</h4>${p.html}<hr><small>${(p.footnotes||[]).map((n,j)=>`${j+1}. ${escapeHtml(n.text)}`).join('<br>')}</small></div>`).join('');download(new Blob([`<html><head><meta charset="utf-8"><style>body{font-family:Georgia}div{min-height:90vh} </style></head><body>${body}</body></html>`],{type:'application/msword'}),(project.title||'ra9mana-document')+'.doc')}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('تم النسخ')).catch(()=>{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('تم النسخ')})}
  function toast(m){const t=$('#toast');if(!t)return;t.querySelector('.toast-inner').textContent=m;t.classList.add('is-visible');setTimeout(()=>t.classList.remove('is-visible'),2200)}
  function updateStats(){let html=$$('.page-content').map(x=>x.innerText).join(' ').trim();const words=html?html.split(/\s+/).filter(Boolean).length:0;const notes=project.pages.reduce((a,p)=>a+(p.footnotes||[]).length,0);$('#word-count').textContent=`${words} ${LANGS[lang()].words}`;$('#page-count').textContent=`${project.pages.length} ${LANGS[lang()].pages}`;$('#footnote-count').textContent=`${notes} ${LANGS[lang()].notes}`}
  function refreshEditorLanguage(){const l=LANGS[lang()];$('#project-title').placeholder=l.new;$('#save-status').textContent=l.saved;updateStats()}
  function init(){loadLibrary();render();refreshEditorLanguage();document.addEventListener('ra9mana:langchange',refreshEditorLanguage);$('#project-title').oninput=()=>persist();$$('.editor-toolbar [data-cmd]').forEach(b=>b.onclick=()=>exec(b.dataset.cmd));$('#block-style').onchange=e=>exec('formatBlock',e.target.value);$('#add-page').onclick=addPage;$('#add-reference').onclick=picker;$('#sidebar-add-ref').onclick=picker;$('#add-footnote').onclick=openFootnote;$('#sidebar-footnote').onclick=openFootnote;$('#show-bibliography').onclick=bibliography;$('#sidebar-bib').onclick=bibliography;$('#ask-ramon').onclick=ramon;$('#new-project').onclick=()=>{capture();project=createProject();render();persist()};$('#open-project').onclick=projectsModal;$('#export-project').onclick=exportProject;$('#import-project').onclick=importProject;$('#print-document').onclick=()=>{capture();window.print()};$('#export-word').onclick=exportWord;$$('[data-close-editor-modal]').forEach(b=>b.onclick=closeModal);document.addEventListener('click',e=>{if(e.target.matches('[data-close-editor-modal]'))closeModal();if(e.target.id==='editor-modal'&&e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();capture();toast('تم الحفظ')}});window.addEventListener('beforeprint',capture);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.RA9MANA_EDITOR={getProject:()=>project};
})();
